import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Theme } from "frosted-ui";
import { WhopThemeProvider } from "@whop-apps/sdk";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-background overscroll-none`}
      >
        <WhopThemeProvider>
          <Theme className="size-full" accentColor="blue">
            {children}
          </Theme>
        </WhopThemeProvider>
      </body>
    </html>
  );
}
