name: Auto Update Documentation

on:
   schedule:
      # Run every hour
      - cron: "0 * * * *"
   workflow_dispatch: # Allow manual trigger

concurrency:
   group: auto-update-docs
   cancel-in-progress: false

jobs:
   update-docs:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4
           with:
              token: ${{ secrets.GH_WRITE_TOKEN }}
              fetch-depth: 0

         - name: Set up pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 9.15.9

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "22.x"
              cache: "pnpm"

         - name: Install dependencies
           run: pnpm install

         - name: Generate OpenAPI docs
           run: pnpm --filter @local/docs generate:openapi

         - name: Generate GraphQL docs
           run: pnpm --filter @local/graphql-codegen-docs generate

         - name: Format with Biome
           run: pnpm biome check --write --no-errors-on-unmatched --files-ignore-unknown=true

         - name: Check for changes
           id: git-check
           run: |
              git add .
              if git diff --staged --quiet; then
                echo "has_changes=false" >> $GITHUB_OUTPUT
              else
                echo "has_changes=true" >> $GITHUB_OUTPUT
              fi

         - name: Create or Update Pull Request
           if: steps.git-check.outputs.has_changes == 'true'
           id: cpr
           uses: peter-evans/create-pull-request@v7
           with:
              token: ${{ secrets.GH_WRITE_TOKEN }}
              commit-message: "docs: auto-update generated documentation"
              branch: auto-update-docs
              delete-branch: true
              title: "[Auto] Update Generated Documentation"
              body: |
                 This PR was automatically generated to update documentation.

                 ## Changes
                 - Updated OpenAPI documentation
                 - Updated GraphQL documentation  
                 - Applied Biome formatting

                 This PR will auto-merge when all checks pass.
              labels: |
                 documentation
                 automated

         - name: Enable auto-merge
           if: steps.git-check.outputs.has_changes == 'true' && steps.cpr.outputs.pull-request-number
           env:
              GH_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
              PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
           run: |
              gh pr merge $PR_NUMBER --auto --squash --delete-branch

         - name: Approve PR (bypass review requirements)
           if: steps.git-check.outputs.has_changes == 'true' && steps.cpr.outputs.pull-request-number
           env:
              GH_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
              PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
           run: |
              # Wait a moment for the PR to be fully created
              sleep 5
              # Approve the PR to satisfy review requirements
              gh pr review $PR_NUMBER --approve --body "Auto-approved by workflow"
