name: Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify your Node.js version
          cache: 'pnpm'
    
      - name: Checkout whop-proto repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WHOP_PROTO_GH_TOKEN }}
          repository: whopio/whop-proto
          sparse-checkout: |
            protos
          path: "protos"
  
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check types
        run: pnpm turbo run check-types --filter=@whop/api... --filter=@whop/checkout...

      - name: Build packages
        run: pnpm turbo run build --filter=@whop/api... --filter=@whop/checkout...